name: Build + Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy Functions App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Config Node Version
        uses: actions/setup-node@master
        with:
          node-version: 20        
      # Runs a single command using the runners shell
      # And of course we need to goto our functions folder to deploy
      - name: Install npm packages
        run: |
          cd functions
          npm install
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v13.7.3
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
